apiVersion: v1
kind: Service
metadata:
  name: node-csv-api
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
  selector:
    app: node-csv-api
